import sys

filepath = 'tcia-remapper.py'
with open(filepath, 'r') as f:
    lines = f.readlines()

new_lines = []
found = False
for line in lines:
    if 'st.header("Tabular Data Standardization")' in line:
        found = True
    if found and '# Footer' in line:
        found = False

    if found:
        continue

    if 'elif st.session_state.phase == 2:' in line:
        new_lines.append(line)
        new_lines.append('    st.header("Tabular Data Standardization")\n')
        new_lines.append('    st.markdown("""\n')
        new_lines.append('    Upload your source data files, map your columns, and standardize values.\n')
        new_lines.append('    """)\n')
        new_lines.append('    \n')
        new_lines.append('    # File upload\n')
        new_lines.append('    uploaded_file = st.file_uploader(\n')
        new_lines.append('        "Upload your source data file (CSV, TSV, or Excel)",\n')
        new_lines.append('        type=[\'csv\', \'tsv\', \'xlsx\', \'xls\']\n')
        new_lines.append('    )\n')
        new_lines.append('    \n')
        new_lines.append('    if uploaded_file is not None:\n')
        new_lines.append('        try:\n')
        new_lines.append('            df = None\n')
        new_lines.append('            if uploaded_file.name.endswith(\'.csv\'):\n')
        new_lines.append('                df = pd.read_csv(uploaded_file)\n')
        new_lines.append('            elif uploaded_file.name.endswith(\'.tsv\'):\n')
        new_lines.append('                df = pd.read_csv(uploaded_file, sep=\'\t\')\n')
        new_lines.append('            else:\n')
        new_lines.append('                excel_file = pd.ExcelFile(uploaded_file)\n')
        new_lines.append('                sheet_names = excel_file.sheet_names\n')
        new_lines.append('                if len(sheet_names) > 1:\n')
        new_lines.append('                    selected_sheet = st.selectbox("Select which sheet to process:", sheet_names)\n')
        new_lines.append('                    df = pd.read_excel(uploaded_file, sheet_name=selected_sheet)\n')
        new_lines.append('                else:\n')
        new_lines.append('                    df = pd.read_excel(uploaded_file)\n')
        new_lines.append('            \n')
        new_lines.append('            if df is not None:\n')
        new_lines.append('                df = df.dropna(how=\'all\').dropna(axis=1, how=\'all\')\n')
        new_lines.append('                if len(df) > 1:\n')
        new_lines.append('                    if df.iloc[0].count() == 1 and df.iloc[1].count() > 1:\n')
        new_lines.append('                        new_header = df.iloc[1]\n')
        new_lines.append('                        df = df[2:]\n')
        new_lines.append('                        df.columns = new_header\n')
        new_lines.append('                df.columns = [str(c).strip() for c in df.columns]\n')
        new_lines.append('                df = df.map(lambda x: x.strip() if isinstance(x, str) else x)\n')
        new_lines.append('                st.session_state.uploaded_data = df\n')
        new_lines.append('                st.success(f"✅ Loaded data with {len(df)} rows and {len(df.columns)} columns")\n')
        new_lines.append('                with st.expander("Preview Data", expanded=True):\n')
        new_lines.append('                    st.dataframe(df.head(10))\n')
        new_lines.append('            \n')
        new_lines.append('            st.markdown("---")\n')
        new_lines.append('            st.subheader("Column Mapping")\n')
        new_lines.append('            all_properties = {}\n')
        new_lines.append('            excluded_entities = list(st.session_state.metadata.keys())\n')
        new_lines.append('            for entity_name, properties in schema.items():\n')
        new_lines.append('                if entity_name in excluded_entities: continue\n')
        new_lines.append('                for prop in properties:\n')
        new_lines.append('                    prop_name = prop[\'Property\']\n')
        new_lines.append('                    if "." in prop_name: continue\n')
        new_lines.append('                    all_properties[f"{entity_name}.{prop_name}"] = prop\n')
        new_lines.append('            \n')
        new_lines.append('            mapping_data = []\n')
        new_lines.append('            for col in df.columns:\n')
        new_lines.append('                cols = st.columns([3, 4, 2])\n')
        new_lines.append('                with cols[0]:\n')
        new_lines.append('                    st.write(f"**{col}**")\n')
        new_lines.append('                    sample_vals = df[col].dropna().unique()[:3]\n')
        new_lines.append('                    st.caption(f"Sample: { \', \'.join(map(str, sample_vals)) }")\n')
        new_lines.append('                with cols[1]:\n')
        new_lines.append('                    current_mapping = next((t for t, s in st.session_state.column_mapping.items() if s == col), None)\n')
        new_lines.append('                    property_options = ["(Skip this column)"] + list(all_properties.keys())\n')
        new_lines.append('                    default_index = property_options.index(current_mapping) if current_mapping in property_options else 0\n')
        new_lines.append('                    selected = st.selectbox("Target Property", options=property_options, index=default_index, key=f"map_{col}", label_visibility="collapsed")\n')
        new_lines.append('                    if selected != "(Skip this column)": mapping_data.append((selected, col))\n')
        new_lines.append('                with cols[2]:\n')
        new_lines.append('                    if selected != "(Skip this column)" and selected in all_properties:\n')
        new_lines.append('                        if all_properties[selected].get(\'Required/optional\') == \'R\': st.write("✅ Required")\n')
        new_lines.append('                        else: st.write("⚪ Optional")\n')
        new_lines.append('            \n')
        new_lines.append('            st.markdown("---")\n')
        new_lines.append('            if st.button("✅ Confirm Mapping", type="primary"):\n')
        new_lines.append('                st.session_state.column_mapping = {target: source for target, source in mapping_data}\n')
        new_lines.append('                st.session_state.structure_approved = True\n')
        new_lines.append('                st.success("✅ Column mapping confirmed!")\n')
        new_lines.append('                conflicts = check_metadata_conflict(st.session_state.metadata, df, st.session_state.column_mapping)\n')
        new_lines.append('                if conflicts:\n')
        new_lines.append('                    st.warning("⚠️ Detected conflicts between uploaded data and metadata:")\n')
        new_lines.append('                    for conflict in conflicts: st.write(f"- {conflict[\'entity\']}.{conflict[\'property\']}: Initial=\'{conflict[\'initial_value\']}\' vs New=\'{conflict[\'new_value\']}\'")\n')
        new_lines.append('            \n')
        new_lines.append('            if st.session_state.structure_approved:\n')
        new_lines.append('                st.markdown("---")\n')
        new_lines.append('                st.subheader("Value Standardization")\n')
        new_lines.append('                df = st.session_state.uploaded_data\n')
        new_lines.append('                primary_id_mappings = {}\n')
        new_lines.append('                for target, source in st.session_state.column_mapping.items():\n')
        new_lines.append('                    if "." in target:\n')
        new_lines.append('                        entity, prop = target.split(".", 1)\n')
        new_lines.append('                        if prop.lower() == f"{entity.lower()}_id" or prop.lower() == "id": primary_id_mappings[entity.lower()] = source\n')
        new_lines.append('                for entity_name, props in schema.items():\n')
        new_lines.append('                    for p in props:\n')
        new_lines.append('                        if "." in p[\'Property\']:\n')
        new_lines.append('                            target_e = p[\'Property\'].split(".")[0].lower()\n')
        new_lines.append('                            if target_e in primary_id_mappings:\n')
        new_lines.append('                                full_p = f"{entity_name}.{p[\'Property\']}"\n')
        new_lines.append('                                if full_p not in st.session_state.column_mapping: st.session_state.column_mapping[full_p] = primary_id_mappings[target_e]\n')
        new_lines.append('                split_data = split_data_by_schema(df, st.session_state.column_mapping, schema)\n')
        new_lines.append('                for entity_name, entity_df in split_data.items():\n')
        new_lines.append('                    for rel_name, rel_info in relationships.items():\n')
        new_lines.append('                        for end in rel_info.get(\'Ends\', []):\n')
        new_lines.append('                            if end[\'Src\'] == entity_name and end[\'Dst\'] in st.session_state.metadata:\n')
        new_lines.append('                                dst_meta = st.session_state.metadata[end[\'Dst\']]\n')
        new_lines.append('                                if dst_meta:\n')
        new_lines.append('                                    dst_l = end[\'Dst\'].lower()\n')
        new_lines.append('                                    link_val = dst_meta[0].get(f"{dst_l}_short_name") or dst_meta[0].get(f"{dst_l}_id")\n')
        new_lines.append('                                    if link_val:\n')
        new_lines.append('                                        linkage_p = next((p[\'Property\'] for p in schema.get(entity_name, []) if p[\'Property\'].lower().startswith(f"{dst_l}.")), None)\n')
        new_lines.append('                                        if linkage_p and linkage_p not in entity_df.columns: entity_df[linkage_p] = link_val\n')
        new_lines.append('                missing_links = [l for l in check_missing_links(split_data, schema, relationships) if l[\'target_entity\'] not in st.session_state.metadata and l[\'target_entity\'] in split_data]\n')
        new_lines.append('                if missing_links:\n')
        new_lines.append('                    st.warning("⚠️ Some uploaded entities are missing required linkages to each other:")\n')
        new_lines.append('                    for l in missing_links: st.write(f"- Entity **{l[\'entity\']}** is missing linkage to **{l[\'target_entity\']}** (Property: )")\n')
        new_lines.append('                for entity_name, entity_df in split_data.items():\n')
        new_lines.append('                    with st.expander(f"📊 {entity_name} ({len(entity_df)} rows)", expanded=True):\n')
        new_lines.append('                        st.dataframe(entity_df.head(10))\n')
        new_lines.append('                        report, corrections = validate_dataframe(entity_df, entity_name, schema, permissible_values)\n')
        new_lines.append('                        if report:\n')
        new_lines.append('                            st.write("**Validation Issues Found:**")\n')
        new_lines.append('                            for item in report[:10]: st.write(f"- {item}")\n')
        new_lines.append('                            if corrections:\n')
        new_lines.append('                                if st.button(f"Apply Corrections to {entity_name}", key=f"apply_{entity_name}"):\n')
        new_lines.append('                                    for col, col_corr in corrections.items(): entity_df[col] = entity_df[col].replace(col_corr)\n')
        new_lines.append('                                    st.success(f"✅ Applied corrections to {entity_name}")\n')
        new_lines.append('                        else: st.success("✅ All values are valid!")\n')
        new_lines.append('                        output_file = os.path.join(st.session_state.output_dir, f"{entity_name.lower()}.tsv")\n')
        new_lines.append('                        entity_df.to_csv(output_file, sep=\'\t\', index=False)\n')
        new_lines.append('                        with open(output_file, \'r\') as f: st.download_button(label=f"Download {entity_name}.tsv", data=f.read(), file_name=f"{entity_name.lower()}.tsv", mime="text/tab-separated-values", key=f"download_{entity_name}")\n')
        new_lines.append('                st.markdown("---")\n')
        new_lines.append('                st.success("🎉 Validation complete!")\n')
        new_lines.append('                if st.button("🔄 Start New Validation"): reset_app(); st.rerun()\n')
        new_lines.append('        except Exception as e: st.error(f"Error: {e}")\n')
        new_lines.append('    else: st.info("👆 Please upload a file to begin.")\n')
        continue

    new_lines.append(line)

with open(filepath, 'w') as f:
    f.writelines(new_lines)
